# fly.toml app configuration file generated for onetime-blog on 2024-10-24T13:37:03-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'onetime-blog'
primary_region = 'ams'

[build]
dockerfile = 'Dockerfile'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 1

[[services.ports]]
handlers = ["http"]
port = 80
force_https = true

