#export default defineAppConfig({
#  ui: {
#    primary: 'brand',
#    gray: 'midnight',
#    footer: {
#      bottom: {
#        left: 'text-sm text-gray-500 dark:text-gray-400',
#        wrapper: 'border-t border-gray-200 dark:border-gray-800'
#      }
#    }
#  },
#  seo: {
#    siteName: 'Onetime Secret - Blog & Documentation'
#  },
#  header: {
#    logo: {
#      alt: '',
#      light: '/onetime-logo-v3-xl.svg',
#      dark: '/onetime-logo-v3-xl.svg'
#    },
#    search: true,
#    colorMode: true,
#    links: [{
#      'icon': 'i-simple-icons-github',
#      'to': 'https://github.com/onetimesecret/',
#      'target': '_blank',
#      'aria-label': 'Docs template on GitHub'
#    }]
#  },
#  footer: {
#    credits: 'Copyright © 2024',
#    colorMode: false,
#    links: [{
#      'icon': 'i-simple-icons:statuspal',
#      'to': 'https://status.onetimesecret.com',
#      'target': '_blank',
#      'aria-label': 'Onetime Secret Status'
#    }]
#  },
#  toc: {
#    title: 'Table of Contents',
#    bottom: {
#      title: 'Community',
#      edit: 'https://github.com/onetimesecret/blog',
#      links: [{
#        icon: 'i-heroicons-star',
#        label: 'Star on GitHub',
#        to: 'https://github.com/onetimesecret/onetimesecret',
#        target: '_blank'
#      }, {
#        icon: 'i-heroicons-book-open',
#        label: 'Onetime Secret docs',
#        to: 'https://docs.onetimesecret.com/',
#        target: '_blank'
#      }, {
#        icon: 'i-simple-icons-nuxtdotjs',
#        label: 'View our plans',
#        to: 'https://onetimesecret.com/pricing',
#        target: '_blank'
#      }]
#    }
#  }
#})


title: 'Onetime Secret - Docs template'
description: Onetime Secret is a collection of premium Vue components built on top of Nuxt UI to create beautiful & responsive Nuxt applications in minutes.
navigation: false
hero:
  title: 'Secure links, stronger connections'
  description: 'Share sensitive information with confidence!'
  orientation: horizontal
  headline:
    label: Check out our plans
    to: https://onetimesecret.com/pricing
    icon: i-heroicons-arrow-top-right-on-square-20-solid
  links:
    - label: Get started
      icon: i-heroicons-arrow-right-20-solid
      trailing: true
      to: '/getting-started'
      size: lg
    - label: Self-hosted
      icon: i-simple-icons-github
      size: lg
      color: gray
      to: https://github.com/onetimesecret/onetimesecret
      target: _blank
  code: |
    ```bash [Terminal]
    onetime create < all-my-base.txt
    ```
features:
  title: 'Privacy-Focused Features'
  links:
    - label: 'Explore Onetime Secret'
      icon: 'OnetimeLogo'
      trailingIcon: 'i-heroicons-arrow-right-20-solid'
      color: 'gray'
      to: 'https://onetimesecret.com'
      target: '_blank'
      size: lg
  items:
    - title: 'Single-use links'
      description: 'Self-destructing messages for ultimate privacy'
      icon: 'i-material-symbols-light:destruction'
      to: 'https://onetimesecret.com/features'
      target: '_blank'
    - title: 'Server-Side Encryption'
      description: 'Your secrets are securely encrypted on our servers'
      icon: 'i-material-symbols-lock-outline'
      to: 'https://onetimesecret.com/security'
      target: '_blank'
    - title: 'Customizable Expiration'
      description: 'Set your secret to expire after a specific time'
      icon: 'i-material-symbols-timer-outline'
      to: 'https://onetimesecret.com/features'
      target: '_blank'
    - title: 'Passphrase Protection'
      description: 'Add an extra layer of security with a custom passphrase'
      icon: 'i-material-symbols:password'
      to: 'https://onetimesecret.com/features'
      target: '_blank'
    - title: 'Custom Domains'
      description: 'Use your own domain for a personalized experience'
      icon: 'i-material-symbols-domain'
      to: 'https://onetimesecret.com/custom-domains'
      target: '_blank'
    - title: 'Open Source'
      description: 'Transparent, community-audited codebase for trust'
      icon: 'i-simple-icons-github'
      to: 'https://github.com/onetimesecret/onetimesecret'
      target: '_blank'
